# Generated by Django 3.0 on 2020-08-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
