# Generated by Django 3.0 on 2020-08-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200806_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_id',
        ),
    ]
