# Generated by Django 3.0 on 2020-08-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='owner',
        ),
    ]
